service: default
runtime: nodejs16
handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html

  - url: /
    static_dir: build

  - url: /news/
    static_files: build/newsroom.html
    upload: build/newsroom.html

  - url: /(.*)
    static_files: build/index.html
    upload: build/index.html

instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.85
  min_instances: 1
  max_instances: 200
  min_pending_latency: 30ms # default value
  max_pending_latency: automatic