service: default
runtime: nodejs16
handlers:

  # newsroom
  - url: /newsroom/
    static_files: build/newsroom.html
    upload: build/newsroom.html

  # presentation
  - url: /presentation/
    static_files: build/presentation.html
    upload: build/presentation.html

  - url: /
    static_files: build/index.html
    upload: build/index.html
    secure: always
    redirect_http_response_code: 301

instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.85
  min_instances: 1
  max_instances: 200
  min_pending_latency: 30ms # default value
  max_pending_latency: automatic